name: Update IPTV 

on:
    schedule:
      - cron: 0 0/12 * * * 
    workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')"

    - name: 直播源
      run: |       
        # gohkh0825
        rm -f ./m3u/LIVE-TV.m3u && wget https://raw.githubusercontent.com/gohkh0825/LIVE-TV/main/LIVE-TV.m3u -O ./m3u/LIVE-TV.m3u
        
        # kiki4177
        rm -f ./m3u/Kiki.m3u && wget https://raw.githubusercontent.com/kiki4177/iptv/main/Kiki -O ./m3u/Kiki.m3u

        
        # 159
        rm -f ./m3u/159.m3u && wget http://www.52sw.top:678/play/oj1381/list.php?get=159 -O ./m3u/159.m3u

        
        # 169
        rm -f ./m3u/169.m3u && wget http://www.52sw.top:678/play/oj1381/list.php?get=169%E7%84%A6%E7%82%B9 -O ./m3u/169.m3u

        
        
       
    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -a -m "${{ steps.date.outputs.date }}"
    - name: Push
      run: git push origin main
