name: Update IPTV and EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:    # Allow manual triggering

jobs:
  update_sources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Current Timestamp
        id: date
        run: echo "::set-output name=date::$(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')"

      - name: Download IPTV Sources
        run: |
          wget -O ./m3u/aseanic.m3u https://raw.githubusercontent.com/aseanic/aseanic.github.io/main/iptv || true
          wget -O ./m3u/mystery75.m3u https://raw.githubusercontent.com/mystery75/streaming/app/tivimate || true
          wget -O ./m3u/xiaotan8.m3u https://raw.githubusercontent.com/xiaotan8/xiaotan8.github.io/main/mytvsuper.m3u || true
          wget -O ./m3u/p3p.txt https://raw.githubusercontent.com/letallthewind/live/main/p3p.txt || true
          wget -O ./m3u/bestv.txt https://raw.githubusercontent.com/letallthewind/live/main/bestv.txt || true
          wget -O ./m3u/iptv.txt https://raw.githubusercontent.com/letallthewind/live/main/iptv.txt || true
          wget -O ./m3u/qttv.txt https://raw.githubusercontent.com/letallthewind/live/main/qttv.txt || true
          wget -O ./m3u/smart.txt https://raw.githubusercontent.com/letallthewind/live/main/smart.txt || true
          wget -O ./m3u/ubtv.txt https://raw.githubusercontent.com/letallthewind/live/main/ubtv.txt || true
          wget -O ./m3u/52top/ysp.m3u http://xg.52sw.top:5000/ysp.m3u || true
          wget -O ./m3u/52top/beesport.m3u http://xg.52sw.top:5000/beesport.m3u || true
          wget -O ./m3u/52top/tptv_proxy.m3u http://xg.52sw.top:5000/tptv_proxy.m3u || true
          wget -O ./m3u/52top/sxg.m3u http://xg.52sw.top:5000/sxg.m3u || true
          wget -O ./m3u/my.m3u https://raw.githubusercontent.com/weareblahs/freeview/main/mytv_broadcasting.m3u8 || true
          wget -O ./m3u/FreeviewMY.m3u8 https://raw.githubusercontent.com/itszairi/FreeviewMY/main/FreeviewMY.m3u8 || true
          

      - name: Download Live Sources
        run: |

          wget -O ./m3u/Kiki.m3u https://raw.githubusercontent.com/kiki4177/iptv/main/Kiki || true
          sed -i '/#EXTM3U/d; /^\s*$/d' ./m3u/Kiki.m3u

          wget -O ./m3u/mewatchsg.m3u8 https://raw.githubusercontent.com/samleong123/mewatchsg/main/mewatchsg_drm_wv_url.m3u8 || true
          sed -i '/#EXTM3U/d; /^\s*$/d' ./m3u/mewatchsg.m3u8
          
          wget -O ./m3u/52top/4gtv.m3u http://xg.52sw.top:5000/4gtv.m3u || true
          sed -i '/#EXTM3U/d; /^\s*$/d' ./m3u/52top/4gtv.m3u
                    
          wget -O ./m3u/52top/itv_proxy.m3u http://xg.52sw.top:5000/itv_proxy.m3u || true
          sed -i '/#EXTM3U/d; /^\s*$/d' ./m3u/52top/itv_proxy.m3u
          
          wget -O ./m3u/52top/mytvsuper.m3u http://xg.52sw.top:5000/mytvsuper.m3u || true
          sed -i '/#EXTM3U/d; /^\s*$/d' ./m3u/52top/mytvsuper.m3u
                    
          # tw
          wget -O ./m3u/tw.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/tw.m3u || true
          sed -i 's/#EXTINF:-1/#EXTINF:-1 group-title="TW"/g; /^\s*$/d' ./m3u/tw.m3u

          # cn
          wget -O ./m3u/cqyx.m3u https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/cqyx.m3u || true
          wget -O ./m3u/sxg.m3u https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/sxg.m3u || true
          sed -i '/#EXTM3U/d' ./m3u/cqyx.m3u ./m3u/sxg.m3u 
          # cat ./m3u/cqyx.m3u ./m3u/sxg.m3u | tee ./m3u/iptv-org.m3u >/dev/null
          # sed -i '/^\s*$/d' ./m3u/iptv-org.m3u

      - name: Download Program Guide
        run: |
          wget -O ./EPG/My.xml https://cutt.ly/FreeviewMY-EPG-1 || true
          wget -O ./EPG/Astro.xml https://cutt.ly/FreeviewMY-EPG-2 || true
          wget -O ./EPG/SG.xml https://raw.githubusercontent.com/AqFad2811/epg/main/singapore.xml || true
          wget 'https://assets.livednow.com/epg.xml' \
          --header='Upgrade-Insecure-Requests: 1' \
          --header='User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
          --header='sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' \
          --header='sec-ch-ua-mobile: ?0' \
          --header='sec-ch-ua-platform: "Windows"' \
          -O ./EPG/CHN.xml || true
          echo "EPG Auto Update in ${{ steps.date.outputs.date }}" > README.md

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: pip install lxml

      - name: Run Python Scripts
        run: |
          python ./.github/workflows/remove_content.py
          python ./.github/workflows/epg.py
          # python ./.github/workflows/group.py
          
      - name: Integrate Master Playlist
        run: |
          rm -f Master.m3u && touch Master.m3u
          cat ./m3u/Kiki.m3u ./m3u/mewatchsg.m3u8 ./m3u/52top/itv_proxy.m3u ./m3u/52top/4gtv.m3u ./m3u/52top/mytvsuper.m3u >> Master.m3u
          sed -i '1i #EXTM3U\n#EXTM3U x-tvg-url="https://raw.githubusercontent.com/Tina-062006/java/main/EPG/EPG.xml"' Master.m3u

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -a -m "${{ steps.date.outputs.date }}"
          git push origin main
